
version: 2

models:

  - name: dim_categories
    description: >
      Dimension table for product categories. Extracted from staging events data.
    columns:

      - name: raw_category_id
        description: "Original unique identifier for the product category"
        tests:
          - not_null
          - unique

      - name: category_code
        description: "All hierarchical category codes associated with the product category, separated by commas"

      - name: category_lvl_1
        description: "First level of hierarchical category (e.g. electronics.smartphone returns electronics)"

      - name: category_lvl_2
        description: "Second level of hierarchical category (e.g. electronics.smartphone returns smartphone)"

      - name: category_lvl_3
        description: "Third level of hierarchical category (if applicable)"

      - name: category_lvl_4
        description: "Fourth level of hierarchical category (if applicable)"
        
  - name: dim_products
    description: >
      Dimension table for products. Extracted from staging events data.
    columns:
      - name: product_id
        description: "Unique identifier for the product"
        tests:
          - not_null
          - unique

      - name: brand
        description: "Brand of the product"

      - name: category_code
        description: "Category code associated with the product"

      - name: category_lvl_1
        description: "First level of hierarchical category associated with the product"

      - name: category_lvl_2
        description: "Second level of hierarchical category associated with the product" 

      - name: category_lvl_3
        description: "Third level of hierarchical category associated with the product"
      
      - name: category_lvl_4
        description: "Fourth level of hierarchical category associated with the product"

  - name: dim_users
    description: >
      Dimension table for users. Extracted from staging events data.
    columns:
      - name: user_id
        description: "Unique identifier for the user"
        tests:
          - not_null
          - unique

      - name: first_event_timestamp
        description: "Timestamp of the user's first interaction with the platform"
        tests:
          - not_null

      - name: first_event_date
        description: "Date of the user's first interaction with the platform"
        tests:
          - not_null

      - name: last_event_timestamp
        description: "Timestamp of the user's most recent interaction with the platform"
        tests:
          - not_null
      
      - name: last_event_date
        description: "Date of the user's most recent interaction with the platform"
        tests:
          - not_null

      - name: session_count
        description: "Total number of sessions initiated by the user"
        tests:
          - not_null
      
      - name: event_count
        description: "Total number of events generated by the user"
        tests:
          - not_null