
name: 'estore'
version: '1.0.0'

profile: 'estore'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"

models:
  estore:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

vars:
  # Churn classification thresholds (days since last purchase)
  churn_threshold_days: 60
  at_risk_threshold_days: 45
  declining_threshold_days: 30
  # Cohort analysis observation window
  cohort_observation_window_days: 90
  # Session timeout threshold (seconds of inactivity before splitting a session)
  session_timeout_seconds: 3600
  session_outlier_ratio: 200

flags:
  send_anonymous_usage_stats: False