
name: 'estore'
version: '1.0.0'

profile: 'estore'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"

models:
  estore:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

flags:
  send_anonymous_usage_stats: False