estore:
  target: dev
  outputs:
    dev:
      dataset: estore
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: '{{  env_var("BQ_KEYFILE_PATH")  }}'
      location: US
      method: service-account
      priority: interactive
      project: mkt-analytics-project
      threads: 2
      type: bigquery